#!/usr/bin/env bash
#Declare x is a number. 0, 1, or other
x=5
#can also do read x
if [ $x = 0 ]
then
	echo "$x"
	echo "x is 0" #change this to be more fun

elif [ $x = 1 ]
then
	echo "$x"
	echo "x is 1" #change to be more fun
fi

if [ $x -gt 1 ] #add and is not zero to make else true
then
	echo "You've gone too far, return to reality"

else
	echo "You're still in my range, phew..."
fi
